//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Twigaten.Web.Locale {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Twigaten.Web.Locale.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   類似画像/画像転載を見つけるやつ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Banner_FindDuplicateImages {
            get {
                return ResourceManager.GetString("Banner_FindDuplicateImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   « トップページに戻る に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_BackTop {
            get {
                return ResourceManager.GetString("Error_BackTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   おやっ、何かがおかしいです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_Title {
            get {
                return ResourceManager.GetString("Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   人気のツイート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Headline_Featured {
            get {
                return ResourceManager.GetString("Headline_Featured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最近1時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Headline_LatestTime {
            get {
                return ResourceManager.GetString("Headline_LatestTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ツイートが見つかりませんでした に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Headline_NoTweetToShow {
            get {
                return ResourceManager.GetString("Headline_NoTweetToShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ツイート&lt;small&gt;({0})&lt;/small&gt;が見つかりませんでした に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Headline_NoTweetToShow_HTML {
            get {
                return ResourceManager.GetString("Headline_NoTweetToShow_HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} のツイート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Headline_OneTweet {
            get {
                return ResourceManager.GetString("Headline_OneTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   あなたにのみ表示されます に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Headline_ShowOnlyToYou {
            get {
                return ResourceManager.GetString("Headline_ShowOnlyToYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   @{0} のタイムライン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Headline_Timeline {
            get {
                return ResourceManager.GetString("Headline_Timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最終更新日時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Headline_TimelineUpdatedAt {
            get {
                return ResourceManager.GetString("Headline_TimelineUpdatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索にかかった時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Headline_TimeToSearch {
            get {
                return ResourceManager.GetString("Headline_TimeToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーが見つかりませんでした に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Headline_UserNotFound {
            get {
                return ResourceManager.GetString("Headline_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   @{0} の検索結果 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Headline_UserSearch {
            get {
                return ResourceManager.GetString("Headline_UserSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   @{0} のツイート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Headline_UserTweet {
            get {
                return ResourceManager.GetString("Headline_UserTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このサイトについて に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   人気のツイート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Featured {
            get {
                return ResourceManager.GetString("Menu_Featured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   おわり に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Login {
            get {
                return ResourceManager.GetString("Menu_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サインアウト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Logout {
            get {
                return ResourceManager.GetString("Menu_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自分のツイート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_MyTweet {
            get {
                return ResourceManager.GetString("Menu_MyTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイムライン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Timeline {
            get {
                return ResourceManager.GetString("Menu_Timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   人気順 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Order_Featured {
            get {
                return ResourceManager.GetString("Order_Featured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   時刻順 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Order_New {
            get {
                return ResourceManager.GetString("Order_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日付指定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Pager_Datetimepicker {
            get {
                return ResourceManager.GetString("Pager_Datetimepicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   除外 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Pager_Hide {
            get {
                return ResourceManager.GetString("Pager_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最新 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Pager_Latest {
            get {
                return ResourceManager.GetString("Pager_Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   « 新しい に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Pager_Newer {
            get {
                return ResourceManager.GetString("Pager_Newer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   古い » に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Pager_Older {
            get {
                return ResourceManager.GetString("Pager_Older", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示件数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Pager_ResultsPerPage {
            get {
                return ResourceManager.GetString("Pager_ResultsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Pager_Show {
            get {
                return ResourceManager.GetString("Pager_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像でググる に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SimilarMedia_GoogleImage {
            get {
                return ResourceManager.GetString("SimilarMedia_GoogleImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全{0}件 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SimilarMedia_ResultCount {
            get {
                return ResourceManager.GetString("SimilarMedia_ResultCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   別ページで見る に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SimilarMedia_SeparatePage {
            get {
                return ResourceManager.GetString("SimilarMedia_SeparatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ぼっち画像 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SimilarMedia_ShowNoDup {
            get {
                return ResourceManager.GetString("SimilarMedia_ShowNoDup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   もっと見る に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SimilarMedia_ViewMore {
            get {
                return ResourceManager.GetString("SimilarMedia_ViewMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このサイトについて に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_About {
            get {
                return ResourceManager.GetString("Title_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   人気のツイートと類似画像 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_Featured {
            get {
                return ResourceManager.GetString("Title_Featured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Twitter上の類似画像/画像転載を見つけるやつ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_FindDuplicateImages {
            get {
                return ResourceManager.GetString("Title_FindDuplicateImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ツイートが見つかりませんでした に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_NoTweetToShow {
            get {
                return ResourceManager.GetString("Title_NoTweetToShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   @{0} のツイートと類似画像 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_OneTweet {
            get {
                return ResourceManager.GetString("Title_OneTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_Search {
            get {
                return ResourceManager.GetString("Title_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サインインしました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_SignIn_Success {
            get {
                return ResourceManager.GetString("Title_SignIn_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   @{0} のタイムライン上の類似画像 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_Timeline {
            get {
                return ResourceManager.GetString("Title_Timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーが見つかりませんでした に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_UserNotFound {
            get {
                return ResourceManager.GetString("Title_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   @{0} のツイートと類似画像 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_UserTweet {
            get {
                return ResourceManager.GetString("Title_UserTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザー名/ツイートURL/画像で検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Top_SearchWith {
            get {
                return ResourceManager.GetString("Top_SearchWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サインインすると に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Top_SignIn {
            get {
                return ResourceManager.GetString("Top_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   なお用途は に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Top_Usage {
            get {
                return ResourceManager.GetString("Top_Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   とは に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Top_WhatIsThis {
            get {
                return ResourceManager.GetString("Top_WhatIsThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ツイート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TweetButton_Tweet {
            get {
                return ResourceManager.GetString("TweetButton_Tweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全て に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserSearch_All {
            get {
                return ResourceManager.GetString("UserSearch_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォローしている に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserSearch_Following {
            get {
                return ResourceManager.GetString("UserSearch_Following", resourceCulture);
            }
        }
        
        /// <summary>
        ///   閲覧可能 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserSearch_Show {
            get {
                return ResourceManager.GetString("UserSearch_Show", resourceCulture);
            }
        }
    }
}
